#Inspiration for OSX from: https://github.com/bjones1/CodeChat/blob/master/.travis.yml
os: linux
language: python
python:
  - 3.6
env:
  global:
  - GETH_URL_LINUX='https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-1.8.0-5f540757.tar.gz'
  - GETH_URL_MACOS='https://gethstore.blob.core.windows.net/builds/geth-darwin-amd64-1.8.0-5f540757.tar.gz'
  - GETH_VERSION='1.8.0'


matrix:
  include:
  - os: osx
    language: generic
    env: INSTALL_TYPE=macpython VERSION=3.6 VENV=venv
  - os: linux
    language: python
    python: '3.6'

cache:
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/.rotkehlchen-test-dir
    - $HOME/.ethash
    - $HOME/.bin

before_install:
  - mkdir -p $HOME/.bin
  - export PATH=$PATH:$HOME/.bin
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./.travis/before_install.sh; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo ./.travis/before_install.sh; fi
  # This needs to be outside of the before_install.sh script or else the environment
  # is not set properly for OSX
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source terryfy/travis_tools.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then get_python_environment $INSTALL_TYPE $VERSION $VENV; fi

install:
  - python -m pip install -U pip
  - pip install -U pip wheel coveralls "coverage<4.4"
  - pip install pytest-travis-fold
  - pip install flake8
  - pip install -r requirements.txt

# Run the tests.
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source terryfy/test_tools.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python -m pytest rotkehlchen; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then coverage run --source rotkehlchen/ -m pytest --travis-fold=always $TEST_TYPE; fi
